// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Notifier", Scope = "member", Target = "MSBackupPipe.Common.BackupPipeSystem.#Restore(MSBackupPipe.Common.ConfigPair,System.Collections.Generic.List`1<MSBackupPipe.Common.ConfigPair>,MSBackupPipe.Common.ConfigPair,MSBackupPipe.Common.IUpdateNotification)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Notifier", Scope = "member", Target = "MSBackupPipe.Common.BackupPipeSystem.#Verify(MSBackupPipe.Common.ConfigPair,System.Collections.Generic.List`1<MSBackupPipe.Common.ConfigPair>,MSBackupPipe.Common.ConfigPair,MSBackupPipe.Common.IUpdateNotification)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Notifier", Scope = "member", Target = "MSBackupPipe.Common.BackupPipeSystem.#HeaderOnly(MSBackupPipe.Common.ConfigPair,System.Collections.Generic.List`1<MSBackupPipe.Common.ConfigPair>,MSBackupPipe.Common.ConfigPair,MSBackupPipe.Common.IUpdateNotification)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Notifier", Scope = "member", Target = "MSBackupPipe.Common.BackupPipeSystem.#FileList(MSBackupPipe.Common.ConfigPair,System.Collections.Generic.List`1<MSBackupPipe.Common.ConfigPair>,MSBackupPipe.Common.ConfigPair,MSBackupPipe.Common.IUpdateNotification)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "MSBackupPipe.Common.BackupPipeSystem.#ReturnByteScale(System.Int64,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "MSBackupPipe.Common.IUpdateNotification.OnConnecting(System.String)", Scope = "member", Target = "MSBackupPipe.Common.SqlThread.#PreConnect(System.String,System.String,System.String,System.Int32,MSBackupPipe.StdPlugins.IBackupDatabase,System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.String>>,System.Int32,MSBackupPipe.Common.IUpdateNotification,System.Int64&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "MSBackupPipe.Common.SqlThread.#PreConnect(System.String,System.String,System.String,System.Int32,MSBackupPipe.StdPlugins.IBackupDatabase,System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.String>>,System.Int32,MSBackupPipe.Common.IUpdateNotification,System.Int64&)")]
